# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  keycloak-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - kc-db:/var/lib/mysql
    networks:
      - kc-network
  keycloak:
    image: bitnami/keycloak:14.0.0
    #volumes:
    #- ./realm-config:/opt/bitnami/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgres
      KEYCLOAK_DATABASE_HOST: keycloak-db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: root
      #KEYCLOAK_EXTRA_ARGS_PREPENDED: --import-realm
      #KEYCLOAK_BIND_ADDRESS: keycloak-db
    depends_on:
      - keycloak-db
    networks:
      - kc-network

    ports:
      - 8080:8080
volumes:
  kc-db:
networks:
  kc-network:
